# First stage: Build stage where we install dependencies
FROM python:3.10-slim as builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Second stage: Production stage where we only have the compiled dependencies
FROM python:3.10-slim
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
WORKDIR /app
COPY . .
EXPOSE 80
ENV PORT=80
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]


