version: '3.8'

services:
  user-service:
    container_name: user-service
    image: 637423235266.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
    restart: always
    ports:
      - "3001:80"
    env_file:
      - .env
    networks:
      - my_network

      

  dataset-service:
    container_name: dataset-service
    image: 637423235266.dkr.ecr.us-east-1.amazonaws.com/dataset-service:latest
    restart: always
    ports:
      - "3002:80"
    env_file:
      - .env
    networks:
      - my_network

  workspace-service:
    container_name: workspace-service
    image: 637423235266.dkr.ecr.us-east-1.amazonaws.com/workspace-service:latest
    restart: always
    ports:
      - "3003:80"
    env_file:
      - .env
    networks:
      - my_network

  embedding-service:
    container_name: embedding-service
    image: zohaibazam58/langchain-embedding-service:latest
    restart: always
    ports:
      - "3004:80"
    env_file:
      - .env
    networks:
      - my_network

  key-management-service:
    container_name: key-management-service
    image: 637423235266.dkr.ecr.us-east-1.amazonaws.com/key-management-service:latest
    restart: always
    ports:
      - "3005:80"
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
